### PR TITLE
Add support for Unix sockets

### PR DESCRIPTION
**Pull request by adellibovi**
## Description
This PR add a new case for the ClientRequest.Options which is `socketPath(String)`

## Motivation and Context
It resolves issues #212 

## How Has This Been Tested?
NA

## Checklist:
- [x] I have submitted a [CLA form](https://github.com/IBM-Swift/CLA)
- [x] If applicable, I have updated the documentation accordingly.
- [x] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Comment by quanvo87** [comment]
@adellibovi The build is failing on Linux Trusty with:

>/home/travis/build/IBM-Swift/Kitura-net/Sources/KituraNet/ClientRequest.swift:411:45: error: use of unresolved identifier 'CURLOPT_UNIX_SOCKET_PATH'
            curlHelperSetOptString(handle!, CURLOPT_UNIX_SOCKET_PATH, UnsafePointer(socketPath))

Perhaps you'll have to import something `#if os(Linux)`?

**Comment by adellibovi** [comment]
@quanvo87 it works fine with Docker and Ubuntu 16.04, could it be something related to that specific image?

**Comment by kweinmeister** [comment]
If you look at the Travis logs, it looks like the 2 failing environments are Swift 3 & 4 on Ubuntu 14.04. It is passing on Ubuntu 16.04.

**Comment by na-gupta** [comment]
CURLOPT_UNIX_SOCKET_PATH was introduced in [curl v7.40](https://curl.haxx.se/libcurl/c/CURLOPT_UNIX_SOCKET_PATH.html). 

Ubuntu 16.04 has [curl v7.47](https://packages.ubuntu.com/xenial/curl) which includes this but 14.04 has [curl v7.35](https://packages.ubuntu.com/trusty/curl) which does not.

**Comment by adellibovi** [comment]
In this case, what should we do? Find a way to dinamicaly support or not this feature depending on the availability of CURLOPT_UNIX_SOCKET_PATH? Or should we require a minimum version of Curl?

**Comment by na-gupta** [comment]
We could not require curl >7.40 as that would break support for ubuntu 14.04.

IMO, dynamically checking for the availability would be the way to go, but I am not aware of a way to do that using swift preprocessor conditionals. I think it would need to be done using a c helper function, for example in https://github.com/IBM-Swift/CCurl/blob/master/shim.h

**Comment by shmuelk** [comment]
I would try adding some logic for this in shim.h. In that file you could test if the appropriate define is defined.

**Comment by adellibovi** [comment]
Ok, I opened this PR: https://github.com/IBM-Swift/CCurl/pull/13, I will update this PR to momentary point to that a branch with that change.

**Comment by adellibovi** [comment]
I opened a PR about it: https://github.com/IBM-Swift/CCurl/pull/13 but I am not sure how to check for the availability of CURLOPT_UNIX_SOCKET_PATH

**Comment by adellibovi** [comment]
Hi everyone, sorry for the waiting. I could fix the compiling error with Ubuntu 14.04 😄 It is dependent on https://github.com/IBM-Swift/CCurl/pull/13: How could we move this forward with the review? (I changed momentarily the dependencies to point to my CCurl branch in order to pass travis)
/cc: @kweinmeister

**Comment by adellibovi** [comment]
@billabt or @carlbrown, sorry for bothering, some of you could help with this, please? 😄

**Comment by billabt** [comment]
I’ll try an’ take a look tomorrow morning.

**Comment by djones6** [comment]
@adellibovi Apologies that this stalled for so long. I'd like to resurrect this work as part of adding Unix sockets support to Kitura. If you are still interested in making this contribution, please could you sign the CLA?

I would like to make some changes on top of this so that it is non-breaking: https://github.com/djones6/Kitura-net/commit/357806e0b491f6afcae235644a6e0d0fa8b31e24

**Comment by djones6** [comment]
Delivered via #296
